# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      displayName: Build's displayname
      jobs:
          - job: 'j1'
            steps:
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: |
                  # Write your commands here
                  
                  echo 'Hello world'
    - stage: Test
      displayName: Test's displayname
      jobs:
          - job: 'j2'
            steps:
            - task: Maven@3
              inputs:
                mavenPomFile: 'pom.xml'
                mavenOptions: '-Xmx3072m'
                javaHomeOption: 'JDKVersion'
                jdkVersionOption: '1.8'
                jdkArchitectureOption: 'x64'
                publishJUnitResults: true
                testResultsFiles: '**/surefire-reports/TEST-*.xml'
                goals: 'test'
                testRunTitle: 'j2'
    - stage: RegisterArtifact
      jobs:
          - job: 'j3'
            pool: server
            steps:
            - task: InvokeRESTAPI@1
              inputs:
                connectionType: 'connectedServiceName'
                serviceConnection: 'rohitrometesting2-SnDevOpsProject-Generic Connection'
                method: 'POST'
                body: |
                  {
                    "artifacts": [
                      {
                          "name": "az-artifact1",
                          "version": "1.$(build.buildId)",
                          "semanticVersion": "1.$(build.buildId).0",
                          "repositoryName": "repo1"
                      },
                      {
                          "name": "az-artifact2",
                          "version": "1.$(build.buildId)",
                          "semanticVersion": "1.$(build.buildId).0",
                          "repositoryName": "repo2"
                      }
                    ],
                    "pipelineName": "$(system.teamProject)/$(build.definitionName)",
                    "taskExecutionNumber": "$(build.buildId)",
                    "stageName": "$(system.jobDisplayName)",
                    "branchName": "$(build.sourceBranchName)"
                  }
                urlSuffix: '/api/sn_devops/v1/devops/artifact/registration?orchestrationToolId=dd3d36171b8938108b806395624bcb49'
                waitForCompletion: 'false'
              continueOnError: true
    - stage: RegisterPackage
      jobs:
          - job: 'j4'
            pool: server
            steps:
            - task: InvokeRESTAPI@1
              inputs:
                connectionType: 'connectedServiceName'
                serviceConnection: 'rohitrometesting2-SnDevOpsProject-Generic Connection'
                method: 'POST'
                body: |
                  {
                      "name": "pkg1",
                      "artifacts": [
                      {
                          "name": "az-artifact1",
                          "repositoryName": "repo1",
                          "version": "1.$(build.buildId)",
                          "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                          "taskExecutionNumber":"$(build.buildId)",
                          "stageName":"$(system.jobDisplayName)",
                          "branchName":"$(build.sourceBranchName)"
                      }],
                      "pipelineName":"$(system.teamProject)/$(build.definitionName)",
                      "taskExecutionNumber":"$(build.buildId)",
                      "stageName":"$(system.jobDisplayName)",
                      "branchName":"$(build.sourceBranchName)"
                  }
                urlSuffix: '/api/sn_devops/v1/devops/package/registration?orchestrationToolId=dd3d36171b8938108b806395624bcb49'
                waitForCompletion: 'false'
              continueOnError: true
    - stage: deploy
      # displayName: deploy's displayname
      jobs:
          - job: 'j5'
            pool: server
            steps:
            - task: ServiceNow-DevOps-Server-Change-Acceleration@1
              inputs:
                connectedServiceName: 'rohitrometesting2-SnDevOpsProject-ServiceNow DevOps Service Connection'
                UpstreamJob: 'j4'
